name: 'IndexNow'
on:
  schedule:
    # Set the schedule time
    - cron: '0 9 * * *'
  workflow_dispatch:

jobs:
  check-and-submit:
    runs-on: ubuntu-latest
    steps:
      - name: Setup IndexNow 
      # Generate files dynamically to prevent them from being leaked in public repositories.
      # This example will put the file in the root directory of the site.You may change the location by yourself.
        run: echo ${{ secrets.INDEXNOW_KEY }} > ${{ secrets.INDEXNOW_KEY }}.txt
      - name: indexnow-action
        uses: bojieyang/indexnow-action@v2
        with:
          sitemap-location: 'https://codezpc.github.io/WBSXS-WIKI/sitemap.xml'
          key-location: ${{ secrets.INDEXNOW_KEY_LOCATION }}
          key: ${{ secrets.INDEXNOW_KEY }}
